---
# Основной playbook для установки Docker и развертывания приложений
- name: Install Docker and Deploy Applications
  hosts: all
  become: true  # Выполняем от имени суперпользователя
  vars_files:
    - vars/main.yml  # Загружаем переменные из файла
  
  # Добавляем путь к pip из виртуального окружения
  environment:
    PATH: "/opt/docker-venv/bin:{{ ansible_env.PATH }}"
  
  roles:
    # Роль для установки Docker Engine
    - { role: docker, tags: ['docker'] }
    
    # Роль для развертывания приложения Book Catalog
    - { role: app-deploy, tags: ['app'] }
    
    # Роль для развертывания GitLab
    - { role: gitlab-deploy, tags: ['gitlab'] }