---
# Задачи для установки Docker Engine (универсальная версия)

- name: Determine OS family
  ansible.builtin.set_fact:
    is_debian_family: "{{ ansible_os_family == 'Debian' }}"
    is_redhat_family: "{{ ansible_os_family == 'RedHat' }}"

# ===== Для систем на базе Debian (Ubuntu, Debian) =====
- name: Install required dependencies (Debian family)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: yes
  when: is_debian_family

- name: Add Docker GPG key (Debian family)
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  when: is_debian_family

- name: Add Docker repository (Debian family)
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  when: is_debian_family

# ===== Для систем на базе RedHat (RHEL, CentOS, Fedora) =====
- name: Check SELinux status (RedHat family)
  ansible.builtin.shell: getenforce || echo "Not installed"
  register: selinux_status
  changed_when: false
  failed_when: false
  when: is_redhat_family

- name: Log SELinux status (RedHat family)
  ansible.builtin.debug:
    msg: "SELinux status is: {{ selinux_status.stdout }}"
  when: is_redhat_family

- name: Install required packages (RedHat family)
  ansible.builtin.package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python3-pip
    state: present
  when: is_redhat_family

- name: Add Docker repository for RHEL/CentOS
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: is_redhat_family and (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')

- name: Add Docker repository for Fedora
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: is_redhat_family and ansible_distribution == 'Fedora'

# ===== Общие задачи для всех дистрибутивов =====
- name: Install Docker packages
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present
    update_cache: "{{ is_debian_family }}"

- name: Install python docker modules
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
    state: present

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  notify: Restart Docker