---
# Задачи для установки Docker Engine (универсальная версия)

- name: Determine OS family
  ansible.builtin.set_fact:
    is_debian_family: "{{ ansible_os_family == 'Debian' }}"
    is_redhat_family: "{{ ansible_os_family == 'RedHat' }}"

# ===== Очистка предыдущих конфигураций Docker (Debian) =====
- name: Clean previous Docker repository configurations (Debian family)
  ansible.builtin.shell: |
    rm -f /etc/apt/sources.list.d/docker.list
    rm -f /etc/apt/sources.list.d/docker*.list
    rm -f /usr/share/keyrings/docker-archive-keyring.gpg
    rm -f /etc/apt/keyrings/docker.gpg
  ignore_errors: true
  changed_when: false  # Не отмечать задачу как измененную
  when: is_debian_family

- name: Update apt cache after cleaning (Debian family)
  ansible.builtin.apt:
    update_cache: yes
  when: is_debian_family

# ===== Для систем на базе Debian (Ubuntu, Debian) =====
- name: Install required dependencies (Debian family)
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: yes
  when: is_debian_family

- name: Create keyrings directory (Debian family)
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: is_debian_family

- name: Add Docker GPG key (Debian family)
  ansible.builtin.shell: |
    curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  when: is_debian_family

- name: Add Docker repository (Debian family)
  ansible.builtin.shell: |
    echo "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable" > /etc/apt/sources.list.d/docker.list
  args:
    creates: /etc/apt/sources.list.d/docker.list
  when: is_debian_family
  register: apt_docker_repo

- name: Update apt cache after adding Docker repository (Debian family)
  ansible.builtin.apt:
    update_cache: yes
  when: is_debian_family and apt_docker_repo.changed
  
# ===== Для систем на базе RedHat (RHEL, CentOS, Fedora) =====
- name: Check SELinux status (RedHat family)
  ansible.builtin.shell: getenforce || echo "Not installed"
  register: selinux_status
  changed_when: false
  failed_when: false
  when: is_redhat_family

- name: Log SELinux status (RedHat family)
  ansible.builtin.debug:
    msg: "SELinux status is: {{ selinux_status.stdout }}"
  when: is_redhat_family

- name: Install required packages (RedHat family)
  ansible.builtin.package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - python3-pip
    state: present
  when: is_redhat_family

- name: Add Docker repository for RHEL/CentOS
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: is_redhat_family and (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')

- name: Add Docker repository for Fedora
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  when: is_redhat_family and ansible_distribution == 'Fedora'

# ===== Общие задачи для всех дистрибутивов =====
- name: Install Docker packages
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present
    update_cache: "{{ is_debian_family }}"

- name: Install python docker modules
  ansible.builtin.pip:
    name:
      - docker
      - docker-compose
    state: present

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Add current user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  notify: Restart Docker