---
# Handlers для роли app-deploy

- name: Verify application is running
  ansible.builtin.uri:
    url: https://localhost/api/health
    method: GET
    validate_certs: no  # Не проверяем SSL сертификат, т.к. он самоподписанный
    status_code: 200  # Ожидаем HTTP код 200
  register: health_check
  retries: 5  # Повторяем проверку 5 раз
  delay: 10  # С интервалом 10 секунд
  until: health_check.status == 200
  failed_when: health_check.status != 200  # Проверка считается неудачной, если код != 200

- name: Test application API
  ansible.builtin.uri:
    url: https://localhost/api/authors
    method: POST
    validate_certs: no  # Не проверяем SSL сертификат, т.к. он самоподписанный
    body_format: json
    body:  # Тестовые данные для создания автора
      name: "Test Author"
      bio: "Created by Ansible"
    status_code: 201  # Ожидаем HTTP код 201 (Created)
  register: api_test
  retries: 3  # Повторяем проверку 3 раза
  delay: 5  # С интервалом 5 секунд
  until: api_test.status == 201
  failed_when: api_test.status != 201  # Проверка считается неудачной, если код != 201